GET http://localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2ODk0NDUzNDUsImV4cCI6MTY4OTQ0ODk0NSwiYXVkIjoiNjRiMjhmM2M4MDJkNTNkM2UyMmNhNTI4IiwiaXNzIjoiZHVzaHlhbnQuY29tIn0.eWT4qSyG9nrU_i7O6PghvS70KFTKRAvfibo7bPFANO8


###Login Route
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "dushyant@example.com",
    "password": "123456"
}
